FROM centos:7

# install repos
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    rpm -Uvh https://mirror.webtatic.com/yum/el7/latest.rpm

RUN yum install -y php71w php71w-common php71w-devel php71w-gd php71w-imap \
        php71w-ldap php71w-mbstring php71w-mcrypt \
        php71w-mysqlnd php71w-intl php71w-odbc php71w-opcache php71w-pdo \
        php71w-pear php71w-pecl-apcu php71w-pecl-geoip \
        php71w-pecl-redis php71w-pecl-mongodb php71w-soap php71w-xml \
        php71w-pecl-memcached php71w-pecl-imagick php71w-pecl-xdebug \
