FROM centos:7

# install repos
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum install yum-utils -y

RUN yum install -y git php73-php php73-php-common php73-php-cli php73-php-devel php73-php-gd php73-php-imap \
        php73-php-ldap php73-php-mbstring php73-php-mcrypt \
        php73-php-mysqlnd php73-php-intl php73-php-odbc php73-php-opcache php73-php-pdo \
        php73-php-pear php73-php-pecl-apcu php73-php-pecl-geoip \
        php73-php-pecl-redis php73-php-pecl-mongodb php73-php-soap php73-php-xml \
        php73-php-pecl-memcached php73-php-pecl-imagick php73-php-pecl-xdebug

RUN ln -s /etc/opt/remi/php73/php.ini /etc/php.ini && \
        ln -s /etc/opt/remi/php73/php.d /etc/php.d

#COPY ./conf/php73-php/php.d/ /etc/php.d/
